name: Doviz Agent to Google Sheets

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests beautifulsoup4 gspread google-auth selenium webdriver-manager

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Create service_account.json
        run: printf "%s" "${{ secrets.GOOGLE_SHEETS_KEY_BASE64 }}" | base64 -d > service_account.json

      - name: Run scraper
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: python doviz_agent.py
