name: Doviz Agent to Google Sheets

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          pip install pandas requests beautifulsoup4 gspread google-auth selenium

      - name: Run Script
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: python doviz_agent.py
