name: Doviz Agent to Google Sheets

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          python3 -m pip install --upgrade pip
          pip install pandas requests beautifulsoup4 gspread google-auth selenium

      - name: Create service account file
        run: |
          echo "${{ secrets.GOOGLE_SHEETS_KEY }}" | base64 -d > service_account.json
      
      - name: Run Script
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: python3 doviz_agent.py
