name: Doviz Agent to Google Sheets

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas requests gspread google-auth

      - name: Create service account file from base64
        run: echo "${{ secrets.GOOGLE_SHEETS_KEY_BASE64 }}" | base64 --decode > service_account.json

      - name: Run script
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          EXCHANGE_RATE_KEY: ${{ secrets.EXCHANGE_RATE_KEY }}
        run: python doviz_agent.py
